### ISSUE TITLE
Set scoreboard doesn't support negative value

### ISSUE THREAD

**Issue by MrPlayerYork** [RevonZev/minecraft-python-mcpy#5]
Hey there, so I made a datapack a little bit ago and I was going to try recreating it with your tool. However I've run into a problem where I just want to set a value to a scoreboard variable and it keeps doing it as an operation. Here is my mcpy code:
`unless score @a[limit=1] AotdLoaded = @s AotdLoaded:
    AotdLoaded = -50`
and the output:
`execute unless score @a[limit=1] AotdLoaded = @s AotdLoaded run scoreboard players operation @s AotdLoaded = @s -50`
aaaand what it should be outputting:
`execute unless score @a[limit=1] AotdLoaded = @s AotdLoaded run scoreboard players set @s AotdLoaded -50`

hope this helps explain the issue.

**Comment by MrPlayerYork** [comment]
I have done a little more digging and it seems to do this whenever I try to set a negative number.

**Comment by RevonZev** [comment]
Found the issue. It is because of `^.+\s=\s\d+$` (regex). It is now `^.+\s=\s(-|)\d+$`. This will fix it. Thank you for reporting.

**Comment by MrPlayerYork** [comment]
awesome thanks, is there anything i need to in order to get this working rn or will I have to wait until the next update?
